//
//Copyright 2024 Nokia.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: runner.proto

package runnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_UNKNOWN Operation = 0
	Operation_START   Operation = 1
	Operation_STOP    Operation = 2
	Operation_ERROR   Operation = 3
	Operation_REQUEUE Operation = 4 // Add more operations as needed
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "UNKNOWN",
		1: "START",
		2: "STOP",
		3: "ERROR",
		4: "REQUEUE",
	}
	Operation_value = map[string]int32{
		"UNKNOWN": 0,
		"START":   1,
		"STOP":    2,
		"ERROR":   3,
		"REQUEUE": 4,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_runner_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

type Once_MessageType int32

const (
	Once_PROGRESS_UPDATE Once_MessageType = 0
	Once_ERROR           Once_MessageType = 2
	Once_RUN_RESPONSE    Once_MessageType = 3
	Once_SDC_RESPONSE    Once_MessageType = 4
	Once_COMPLETED       Once_MessageType = 5
)

// Enum value maps for Once_MessageType.
var (
	Once_MessageType_name = map[int32]string{
		0: "PROGRESS_UPDATE",
		2: "ERROR",
		3: "RUN_RESPONSE",
		4: "SDC_RESPONSE",
		5: "COMPLETED",
	}
	Once_MessageType_value = map[string]int32{
		"PROGRESS_UPDATE": 0,
		"ERROR":           2,
		"RUN_RESPONSE":    3,
		"SDC_RESPONSE":    4,
		"COMPLETED":       5,
	}
)

func (x Once_MessageType) Enum() *Once_MessageType {
	p := new(Once_MessageType)
	*p = x
	return p
}

func (x Once_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Once_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_proto_enumTypes[1].Descriptor()
}

func (Once_MessageType) Type() protoreflect.EnumType {
	return &file_runner_proto_enumTypes[1]
}

func (x Once_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Once_MessageType.Descriptor instead.
func (Once_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 0}
}

// Start start choreo
// Removed branch since we only allow checkedout -> RW, other branches are RO
type Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Start) Reset() {
	*x = Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

// Removed branch since we only allow checkedout -> RW, other branches are RO
type Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stop) Reset() {
	*x = Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1}
}

// Removed branch since we only allow checkedout -> RW, other branches are RO
type Once struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Once) Reset() {
	*x = Once{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once) ProtoMessage() {}

func (x *Once) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once.ProtoReflect.Descriptor instead.
func (*Once) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2}
}

type Load struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Load) Reset() {
	*x = Load{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Load) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Load) ProtoMessage() {}

func (x *Load) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Load.ProtoReflect.Descriptor instead.
func (*Load) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{3}
}

type ReconcileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReconcilerName string                 `protobuf:"bytes,1,opt,name=reconcilerName,proto3" json:"reconcilerName,omitempty"`
	ReconcilerUID  string                 `protobuf:"bytes,2,opt,name=reconcilerUID,proto3" json:"reconcilerUID,omitempty"`
	EventTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	Operation      Operation              `protobuf:"varint,4,opt,name=operation,proto3,enum=runnerpb.Operation" json:"operation,omitempty"`
	Success        bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Resource       *Resource              `protobuf:"bytes,7,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *ReconcileResult) Reset() {
	*x = ReconcileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconcileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResult) ProtoMessage() {}

func (x *ReconcileResult) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResult.ProtoReflect.Descriptor instead.
func (*ReconcileResult) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{4}
}

func (x *ReconcileResult) GetReconcilerName() string {
	if x != nil {
		return x.ReconcilerName
	}
	return ""
}

func (x *ReconcileResult) GetReconcilerUID() string {
	if x != nil {
		return x.ReconcilerUID
	}
	return ""
}

func (x *ReconcileResult) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *ReconcileResult) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_UNKNOWN
}

func (x *ReconcileResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReconcileResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReconcileResult) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group     string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Kind      string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{5}
}

func (x *Resource) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Start_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Start_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Start_Request) Reset() {
	*x = Start_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start_Request) ProtoMessage() {}

func (x *Start_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start_Request.ProtoReflect.Descriptor instead.
func (*Start_Request) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Start_Request) GetOptions() *Start_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Start_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Start_Response) Reset() {
	*x = Start_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start_Response) ProtoMessage() {}

func (x *Start_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start_Response.ProtoReflect.Descriptor instead.
func (*Start_Response) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0, 1}
}

type Start_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Start_Options) Reset() {
	*x = Start_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start_Options) ProtoMessage() {}

func (x *Start_Options) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start_Options.ProtoReflect.Descriptor instead.
func (*Start_Options) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Start_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Start_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Stop_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Stop_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Stop_Request) Reset() {
	*x = Stop_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop_Request) ProtoMessage() {}

func (x *Stop_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop_Request.ProtoReflect.Descriptor instead.
func (*Stop_Request) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Stop_Request) GetOptions() *Stop_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Stop_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stop_Response) Reset() {
	*x = Stop_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop_Response) ProtoMessage() {}

func (x *Stop_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop_Response.ProtoReflect.Descriptor instead.
func (*Stop_Response) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1, 1}
}

type Stop_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Stop_Options) Reset() {
	*x = Stop_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop_Options) ProtoMessage() {}

func (x *Stop_Options) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop_Options.ProtoReflect.Descriptor instead.
func (*Stop_Options) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Stop_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Stop_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Once_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Once_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Once_Request) Reset() {
	*x = Once_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once_Request) ProtoMessage() {}

func (x *Once_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once_Request.ProtoReflect.Descriptor instead.
func (*Once_Request) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Once_Request) GetOptions() *Once_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Once_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Once_Options) Reset() {
	*x = Once_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once_Options) ProtoMessage() {}

func (x *Once_Options) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once_Options.ProtoReflect.Descriptor instead.
func (*Once_Options) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Once_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Once_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Once_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Once_MessageType `protobuf:"varint,1,opt,name=Type,proto3,enum=runnerpb.Once_MessageType" json:"Type,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Once_Response_ProgressUpdate
	//	*Once_Response_Error
	//	*Once_Response_RunResponse
	//	*Once_Response_SdcResponse
	Data isOnce_Response_Data `protobuf_oneof:"data"`
}

func (x *Once_Response) Reset() {
	*x = Once_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once_Response) ProtoMessage() {}

func (x *Once_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once_Response.ProtoReflect.Descriptor instead.
func (*Once_Response) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Once_Response) GetType() Once_MessageType {
	if x != nil {
		return x.Type
	}
	return Once_PROGRESS_UPDATE
}

func (m *Once_Response) GetData() isOnce_Response_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Once_Response) GetProgressUpdate() *Once_ProgressUpdate {
	if x, ok := x.GetData().(*Once_Response_ProgressUpdate); ok {
		return x.ProgressUpdate
	}
	return nil
}

func (x *Once_Response) GetError() *Once_Error {
	if x, ok := x.GetData().(*Once_Response_Error); ok {
		return x.Error
	}
	return nil
}

func (x *Once_Response) GetRunResponse() *Once_RunResponse {
	if x, ok := x.GetData().(*Once_Response_RunResponse); ok {
		return x.RunResponse
	}
	return nil
}

func (x *Once_Response) GetSdcResponse() *Once_SDCResponse {
	if x, ok := x.GetData().(*Once_Response_SdcResponse); ok {
		return x.SdcResponse
	}
	return nil
}

type isOnce_Response_Data interface {
	isOnce_Response_Data()
}

type Once_Response_ProgressUpdate struct {
	ProgressUpdate *Once_ProgressUpdate `protobuf:"bytes,2,opt,name=progressUpdate,proto3,oneof"`
}

type Once_Response_Error struct {
	Error *Once_Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Once_Response_RunResponse struct {
	RunResponse *Once_RunResponse `protobuf:"bytes,4,opt,name=runResponse,proto3,oneof"`
}

type Once_Response_SdcResponse struct {
	SdcResponse *Once_SDCResponse `protobuf:"bytes,5,opt,name=sdcResponse,proto3,oneof"`
}

func (*Once_Response_ProgressUpdate) isOnce_Response_Data() {}

func (*Once_Response_Error) isOnce_Response_Data() {}

func (*Once_Response_RunResponse) isOnce_Response_Data() {}

func (*Once_Response_SdcResponse) isOnce_Response_Data() {}

type Once_ProgressUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Once_ProgressUpdate) Reset() {
	*x = Once_ProgressUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once_ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once_ProgressUpdate) ProtoMessage() {}

func (x *Once_ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once_ProgressUpdate.ProtoReflect.Descriptor instead.
func (*Once_ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Once_ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Once_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Once_Error) Reset() {
	*x = Once_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once_Error) ProtoMessage() {}

func (x *Once_Error) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once_Error.ProtoReflect.Descriptor instead.
func (*Once_Error) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Once_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Once_RunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results []*Once_RunResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *Once_RunResponse) Reset() {
	*x = Once_RunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once_RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once_RunResponse) ProtoMessage() {}

func (x *Once_RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once_RunResponse.ProtoReflect.Descriptor instead.
func (*Once_RunResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 5}
}

func (x *Once_RunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Once_RunResponse) GetResults() []*Once_RunResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type Once_RunResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReconcilerRunner string             `protobuf:"bytes,1,opt,name=reconcilerRunner,proto3" json:"reconcilerRunner,omitempty"`
	Success          bool               `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	TaskId           string             `protobuf:"bytes,3,opt,name=taskId,proto3" json:"taskId,omitempty"` // reconcilername + group + kind + namespace + name when failed
	Message          string             `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ExecutionTime    string             `protobuf:"bytes,5,opt,name=executionTime,proto3" json:"executionTime,omitempty"`
	Results          []*ReconcileResult `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *Once_RunResult) Reset() {
	*x = Once_RunResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once_RunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once_RunResult) ProtoMessage() {}

func (x *Once_RunResult) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once_RunResult.ProtoReflect.Descriptor instead.
func (*Once_RunResult) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 6}
}

func (x *Once_RunResult) GetReconcilerRunner() string {
	if x != nil {
		return x.ReconcilerRunner
	}
	return ""
}

func (x *Once_RunResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Once_RunResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Once_RunResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Once_RunResult) GetExecutionTime() string {
	if x != nil {
		return x.ExecutionTime
	}
	return ""
}

func (x *Once_RunResult) GetResults() []*ReconcileResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type Once_SDCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Once_SDCResponse) Reset() {
	*x = Once_SDCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Once_SDCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Once_SDCResponse) ProtoMessage() {}

func (x *Once_SDCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Once_SDCResponse.ProtoReflect.Descriptor instead.
func (*Once_SDCResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2, 7}
}

func (x *Once_SDCResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Load_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Load_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Load_Request) Reset() {
	*x = Load_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Load_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Load_Request) ProtoMessage() {}

func (x *Load_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Load_Request.ProtoReflect.Descriptor instead.
func (*Load_Request) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Load_Request) GetOptions() *Load_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Load_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object []byte `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *Load_Response) Reset() {
	*x = Load_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Load_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Load_Response) ProtoMessage() {}

func (x *Load_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Load_Response.ProtoReflect.Descriptor instead.
func (*Load_Response) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Load_Response) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

type Load_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Load_Options) Reset() {
	*x = Load_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runner_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Load_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Load_Options) ProtoMessage() {}

func (x *Load_Options) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Load_Options.ProtoReflect.Descriptor instead.
func (*Load_Options) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Load_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Load_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

var File_runner_proto protoreflect.FileDescriptor

var file_runner_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x1a, 0x3c, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x4f, 0x0a,
	0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xa0,
	0x01, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x1a, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x22, 0xe8, 0x07, 0x0a, 0x04, 0x4f, 0x6e, 0x63, 0x65, 0x1a, 0x3b, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70,
	0x62, 0x2e, 0x4f, 0x6e, 0x63, 0x65, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0xb9, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4f,
	0x6e, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0e,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2c,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x63, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3e, 0x0a, 0x0b,
	0x72, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x63,
	0x65, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x72, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b,
	0x73, 0x64, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x63,
	0x65, 0x2e, 0x53, 0x44, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x73, 0x64, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x2a, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x21, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x5b, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x32, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x63, 0x65, 0x2e, 0x52, 0x75,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x1a, 0xde, 0x01, 0x0a, 0x09, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2a,
	0x0a, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x63,
	0x69, 0x6c, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x1a, 0x27, 0x0a, 0x0b, 0x53, 0x44, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x60, 0x0a, 0x0b, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x4f,
	0x47, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x55, 0x4e,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x44, 0x43, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x04, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x05, 0x22, 0xb8, 0x01, 0x0a,
	0x04, 0x4c, 0x6f, 0x61, 0x64, 0x1a, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x30, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x1a, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xb0, 0x02, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x63, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x72,
	0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65,
	0x72, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x6f,
	0x6e, 0x63, 0x69, 0x6c, 0x65, 0x72, 0x55, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70,
	0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x66, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x2a, 0x45, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x55, 0x45, 0x10, 0x04, 0x32, 0xf9, 0x01, 0x0a, 0x06, 0x52, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x17, 0x2e,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x16, 0x2e, 0x72, 0x75, 0x6e,
	0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x6f, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a,
	0x04, 0x4f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62,
	0x2e, 0x4f, 0x6e, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4f, 0x6e, 0x63, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x04, 0x4c, 0x6f,
	0x61, 0x64, 0x12, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c, 0x6f,
	0x61, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x75, 0x6e,
	0x6e, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x66, 0x6f, 0x72, 0x6d, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x68,
	0x6f, 0x72, 0x65, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runner_proto_rawDescOnce sync.Once
	file_runner_proto_rawDescData = file_runner_proto_rawDesc
)

func file_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_rawDescData = protoimpl.X.CompressGZIP(file_runner_proto_rawDescData)
	})
	return file_runner_proto_rawDescData
}

var file_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_runner_proto_goTypes = []interface{}{
	(Operation)(0),                // 0: runnerpb.Operation
	(Once_MessageType)(0),         // 1: runnerpb.Once.MessageType
	(*Start)(nil),                 // 2: runnerpb.Start
	(*Stop)(nil),                  // 3: runnerpb.Stop
	(*Once)(nil),                  // 4: runnerpb.Once
	(*Load)(nil),                  // 5: runnerpb.Load
	(*ReconcileResult)(nil),       // 6: runnerpb.ReconcileResult
	(*Resource)(nil),              // 7: runnerpb.Resource
	(*Start_Request)(nil),         // 8: runnerpb.Start.Request
	(*Start_Response)(nil),        // 9: runnerpb.Start.Response
	(*Start_Options)(nil),         // 10: runnerpb.Start.Options
	(*Stop_Request)(nil),          // 11: runnerpb.Stop.Request
	(*Stop_Response)(nil),         // 12: runnerpb.Stop.Response
	(*Stop_Options)(nil),          // 13: runnerpb.Stop.Options
	(*Once_Request)(nil),          // 14: runnerpb.Once.Request
	(*Once_Options)(nil),          // 15: runnerpb.Once.Options
	(*Once_Response)(nil),         // 16: runnerpb.Once.Response
	(*Once_ProgressUpdate)(nil),   // 17: runnerpb.Once.ProgressUpdate
	(*Once_Error)(nil),            // 18: runnerpb.Once.Error
	(*Once_RunResponse)(nil),      // 19: runnerpb.Once.RunResponse
	(*Once_RunResult)(nil),        // 20: runnerpb.Once.RunResult
	(*Once_SDCResponse)(nil),      // 21: runnerpb.Once.SDCResponse
	(*Load_Request)(nil),          // 22: runnerpb.Load.Request
	(*Load_Response)(nil),         // 23: runnerpb.Load.Response
	(*Load_Options)(nil),          // 24: runnerpb.Load.Options
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
}
var file_runner_proto_depIdxs = []int32{
	25, // 0: runnerpb.ReconcileResult.eventTime:type_name -> google.protobuf.Timestamp
	0,  // 1: runnerpb.ReconcileResult.operation:type_name -> runnerpb.Operation
	7,  // 2: runnerpb.ReconcileResult.resource:type_name -> runnerpb.Resource
	10, // 3: runnerpb.Start.Request.options:type_name -> runnerpb.Start.Options
	13, // 4: runnerpb.Stop.Request.options:type_name -> runnerpb.Stop.Options
	15, // 5: runnerpb.Once.Request.options:type_name -> runnerpb.Once.Options
	1,  // 6: runnerpb.Once.Response.Type:type_name -> runnerpb.Once.MessageType
	17, // 7: runnerpb.Once.Response.progressUpdate:type_name -> runnerpb.Once.ProgressUpdate
	18, // 8: runnerpb.Once.Response.error:type_name -> runnerpb.Once.Error
	19, // 9: runnerpb.Once.Response.runResponse:type_name -> runnerpb.Once.RunResponse
	21, // 10: runnerpb.Once.Response.sdcResponse:type_name -> runnerpb.Once.SDCResponse
	20, // 11: runnerpb.Once.RunResponse.results:type_name -> runnerpb.Once.RunResult
	6,  // 12: runnerpb.Once.RunResult.results:type_name -> runnerpb.ReconcileResult
	24, // 13: runnerpb.Load.Request.options:type_name -> runnerpb.Load.Options
	8,  // 14: runnerpb.Runner.Start:input_type -> runnerpb.Start.Request
	11, // 15: runnerpb.Runner.Stop:input_type -> runnerpb.Stop.Request
	14, // 16: runnerpb.Runner.Once:input_type -> runnerpb.Once.Request
	22, // 17: runnerpb.Runner.Load:input_type -> runnerpb.Load.Request
	9,  // 18: runnerpb.Runner.Start:output_type -> runnerpb.Start.Response
	12, // 19: runnerpb.Runner.Stop:output_type -> runnerpb.Stop.Response
	16, // 20: runnerpb.Runner.Once:output_type -> runnerpb.Once.Response
	23, // 21: runnerpb.Runner.Load:output_type -> runnerpb.Load.Response
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_runner_proto_init() }
func file_runner_proto_init() {
	if File_runner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Load); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconcileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once_ProgressUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once_RunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once_RunResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Once_SDCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Load_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Load_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runner_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Load_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_runner_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*Once_Response_ProgressUpdate)(nil),
		(*Once_Response_Error)(nil),
		(*Once_Response_RunResponse)(nil),
		(*Once_Response_SdcResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runner_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_depIdxs,
		EnumInfos:         file_runner_proto_enumTypes,
		MessageInfos:      file_runner_proto_msgTypes,
	}.Build()
	File_runner_proto = out.File
	file_runner_proto_rawDesc = nil
	file_runner_proto_goTypes = nil
	file_runner_proto_depIdxs = nil
}
