//
//Copyright 2024 Nokia.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.0
// source: branch.proto

package branchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Diff_FileAction int32

const (
	Diff_ADDED    Diff_FileAction = 0
	Diff_MODIFIED Diff_FileAction = 1
	Diff_DELETED  Diff_FileAction = 2
)

// Enum value maps for Diff_FileAction.
var (
	Diff_FileAction_name = map[int32]string{
		0: "ADDED",
		1: "MODIFIED",
		2: "DELETED",
	}
	Diff_FileAction_value = map[string]int32{
		"ADDED":    0,
		"MODIFIED": 1,
		"DELETED":  2,
	}
)

func (x Diff_FileAction) Enum() *Diff_FileAction {
	p := new(Diff_FileAction)
	*p = x
	return p
}

func (x Diff_FileAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Diff_FileAction) Descriptor() protoreflect.EnumDescriptor {
	return file_branch_proto_enumTypes[0].Descriptor()
}

func (Diff_FileAction) Type() protoreflect.EnumType {
	return &file_branch_proto_enumTypes[0]
}

func (x Diff_FileAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Diff_FileAction.Descriptor instead.
func (Diff_FileAction) EnumDescriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{6, 0}
}

type Watch_EventType int32

const (
	Watch_ERROR    Watch_EventType = 0
	Watch_ADDED    Watch_EventType = 1
	Watch_MODIFIED Watch_EventType = 2
	Watch_DELETED  Watch_EventType = 3
	Watch_BOOKMARK Watch_EventType = 4
)

// Enum value maps for Watch_EventType.
var (
	Watch_EventType_name = map[int32]string{
		0: "ERROR",
		1: "ADDED",
		2: "MODIFIED",
		3: "DELETED",
		4: "BOOKMARK",
	}
	Watch_EventType_value = map[string]int32{
		"ERROR":    0,
		"ADDED":    1,
		"MODIFIED": 2,
		"DELETED":  3,
		"BOOKMARK": 4,
	}
)

func (x Watch_EventType) Enum() *Watch_EventType {
	p := new(Watch_EventType)
	*p = x
	return p
}

func (x Watch_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Watch_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_branch_proto_enumTypes[1].Descriptor()
}

func (Watch_EventType) Type() protoreflect.EnumType {
	return &file_branch_proto_enumTypes[1]
}

func (x Watch_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Watch_EventType.Descriptor instead.
func (Watch_EventType) EnumDescriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{9, 0}
}

type BranchObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CheckedOut bool   `protobuf:"varint,2,opt,name=checkedOut,proto3" json:"checkedOut,omitempty"`
}

func (x *BranchObject) Reset() {
	*x = BranchObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchObject) ProtoMessage() {}

func (x *BranchObject) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchObject.ProtoReflect.Descriptor instead.
func (*BranchObject) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{0}
}

func (x *BranchObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BranchObject) GetCheckedOut() bool {
	if x != nil {
		return x.CheckedOut
	}
	return false
}

type Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Get) Reset() {
	*x = Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{1}
}

type List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *List) Reset() {
	*x = List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{2}
}

type Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Create) Reset() {
	*x = Create{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{3}
}

type Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Delete) Reset() {
	*x = Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{4}
}

type Merge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Merge) Reset() {
	*x = Merge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merge) ProtoMessage() {}

func (x *Merge) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merge.ProtoReflect.Descriptor instead.
func (*Merge) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{5}
}

type Diff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Diff) Reset() {
	*x = Diff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff) ProtoMessage() {}

func (x *Diff) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff.ProtoReflect.Descriptor instead.
func (*Diff) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{6}
}

type Stash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stash) Reset() {
	*x = Stash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stash) ProtoMessage() {}

func (x *Stash) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stash.ProtoReflect.Descriptor instead.
func (*Stash) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{7}
}

type Checkout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Checkout) Reset() {
	*x = Checkout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checkout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout) ProtoMessage() {}

func (x *Checkout) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout.ProtoReflect.Descriptor instead.
func (*Checkout) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{8}
}

type Watch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Watch) Reset() {
	*x = Watch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch) ProtoMessage() {}

func (x *Watch) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch.ProtoReflect.Descriptor instead.
func (*Watch) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{9}
}

type Get_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch  string       `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Options *Get_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Get_Request) Reset() {
	*x = Get_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Request) ProtoMessage() {}

func (x *Get_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Request.ProtoReflect.Descriptor instead.
func (*Get_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Get_Request) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Get_Request) GetOptions() *Get_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Get_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BranchObj *BranchObject `protobuf:"bytes,1,opt,name=branchObj,proto3" json:"branchObj,omitempty"`
	Logs      []*Get_Log    `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *Get_Response) Reset() {
	*x = Get_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Response) ProtoMessage() {}

func (x *Get_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Response.ProtoReflect.Descriptor instead.
func (*Get_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Get_Response) GetBranchObj() *BranchObject {
	if x != nil {
		return x.BranchObj
	}
	return nil
}

func (x *Get_Response) GetLogs() []*Get_Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Get_Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitHash  string `protobuf:"bytes,1,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	AuthorName  string `protobuf:"bytes,2,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorEmail string `protobuf:"bytes,3,opt,name=authorEmail,proto3" json:"authorEmail,omitempty"`
	Date        string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Message     string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Get_Log) Reset() {
	*x = Get_Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Log) ProtoMessage() {}

func (x *Get_Log) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Log.ProtoReflect.Descriptor instead.
func (*Get_Log) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Get_Log) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *Get_Log) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Get_Log) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *Get_Log) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Get_Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Get_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Get_File) Reset() {
	*x = Get_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_File) ProtoMessage() {}

func (x *Get_File) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_File.ProtoReflect.Descriptor instead.
func (*Get_File) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Get_File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Get_File) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Get_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Get_Options) Reset() {
	*x = Get_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Options) ProtoMessage() {}

func (x *Get_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Options.ProtoReflect.Descriptor instead.
func (*Get_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{1, 4}
}

func (x *Get_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Get_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type List_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *List_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *List_Request) Reset() {
	*x = List_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List_Request) ProtoMessage() {}

func (x *List_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List_Request.ProtoReflect.Descriptor instead.
func (*List_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{2, 0}
}

func (x *List_Request) GetOptions() *List_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type List_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BranchObjects []*BranchObject `protobuf:"bytes,1,rep,name=branchObjects,proto3" json:"branchObjects,omitempty"`
}

func (x *List_Response) Reset() {
	*x = List_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List_Response) ProtoMessage() {}

func (x *List_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List_Response.ProtoReflect.Descriptor instead.
func (*List_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{2, 1}
}

func (x *List_Response) GetBranchObjects() []*BranchObject {
	if x != nil {
		return x.BranchObjects
	}
	return nil
}

type List_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *List_Options) Reset() {
	*x = List_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List_Options) ProtoMessage() {}

func (x *List_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List_Options.ProtoReflect.Descriptor instead.
func (*List_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{2, 2}
}

func (x *List_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *List_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Create_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch  string          `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Options *Create_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Create_Request) Reset() {
	*x = Create_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Request) ProtoMessage() {}

func (x *Create_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Request.ProtoReflect.Descriptor instead.
func (*Create_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Create_Request) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Create_Request) GetOptions() *Create_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Create_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Create_Response) Reset() {
	*x = Create_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Response) ProtoMessage() {}

func (x *Create_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Response.ProtoReflect.Descriptor instead.
func (*Create_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{3, 1}
}

type Create_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Create_Options) Reset() {
	*x = Create_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Options) ProtoMessage() {}

func (x *Create_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Options.ProtoReflect.Descriptor instead.
func (*Create_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Create_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Create_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Delete_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch  string          `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Options *Delete_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Delete_Request) Reset() {
	*x = Delete_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete_Request) ProtoMessage() {}

func (x *Delete_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete_Request.ProtoReflect.Descriptor instead.
func (*Delete_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Delete_Request) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Delete_Request) GetOptions() *Delete_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Delete_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Delete_Response) Reset() {
	*x = Delete_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete_Response) ProtoMessage() {}

func (x *Delete_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete_Response.ProtoReflect.Descriptor instead.
func (*Delete_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{4, 1}
}

type Delete_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Delete_Options) Reset() {
	*x = Delete_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete_Options) ProtoMessage() {}

func (x *Delete_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete_Options.ProtoReflect.Descriptor instead.
func (*Delete_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Delete_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Delete_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Merge_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcBranch string         `protobuf:"bytes,1,opt,name=srcBranch,proto3" json:"srcBranch,omitempty"`
	DstBranch string         `protobuf:"bytes,2,opt,name=dstBranch,proto3" json:"dstBranch,omitempty"`
	Options   *Merge_Options `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Merge_Request) Reset() {
	*x = Merge_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merge_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merge_Request) ProtoMessage() {}

func (x *Merge_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merge_Request.ProtoReflect.Descriptor instead.
func (*Merge_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Merge_Request) GetSrcBranch() string {
	if x != nil {
		return x.SrcBranch
	}
	return ""
}

func (x *Merge_Request) GetDstBranch() string {
	if x != nil {
		return x.DstBranch
	}
	return ""
}

func (x *Merge_Request) GetOptions() *Merge_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Merge_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Merge_Response) Reset() {
	*x = Merge_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merge_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merge_Response) ProtoMessage() {}

func (x *Merge_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merge_Response.ProtoReflect.Descriptor instead.
func (*Merge_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{5, 1}
}

type Merge_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Merge_Options) Reset() {
	*x = Merge_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merge_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merge_Options) ProtoMessage() {}

func (x *Merge_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merge_Options.ProtoReflect.Descriptor instead.
func (*Merge_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Merge_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Merge_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Diff_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcBranch string        `protobuf:"bytes,1,opt,name=srcBranch,proto3" json:"srcBranch,omitempty"`
	DstBranch string        `protobuf:"bytes,2,opt,name=dstBranch,proto3" json:"dstBranch,omitempty"`
	Options   *Diff_Options `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Diff_Request) Reset() {
	*x = Diff_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diff_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff_Request) ProtoMessage() {}

func (x *Diff_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff_Request.ProtoReflect.Descriptor instead.
func (*Diff_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Diff_Request) GetSrcBranch() string {
	if x != nil {
		return x.SrcBranch
	}
	return ""
}

func (x *Diff_Request) GetDstBranch() string {
	if x != nil {
		return x.DstBranch
	}
	return ""
}

func (x *Diff_Request) GetOptions() *Diff_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Diff_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diffs []*Diff_Diff `protobuf:"bytes,1,rep,name=diffs,proto3" json:"diffs,omitempty"`
}

func (x *Diff_Response) Reset() {
	*x = Diff_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diff_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff_Response) ProtoMessage() {}

func (x *Diff_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff_Response.ProtoReflect.Descriptor instead.
func (*Diff_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Diff_Response) GetDiffs() []*Diff_Diff {
	if x != nil {
		return x.Diffs
	}
	return nil
}

type Diff_Diff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcFileName string          `protobuf:"bytes,1,opt,name=srcFileName,proto3" json:"srcFileName,omitempty"`
	DstFileName string          `protobuf:"bytes,2,opt,name=dstFileName,proto3" json:"dstFileName,omitempty"`
	Action      Diff_FileAction `protobuf:"varint,3,opt,name=Action,proto3,enum=branchpb.Diff_FileAction" json:"Action,omitempty"`
}

func (x *Diff_Diff) Reset() {
	*x = Diff_Diff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diff_Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff_Diff) ProtoMessage() {}

func (x *Diff_Diff) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff_Diff.ProtoReflect.Descriptor instead.
func (*Diff_Diff) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{6, 2}
}

func (x *Diff_Diff) GetSrcFileName() string {
	if x != nil {
		return x.SrcFileName
	}
	return ""
}

func (x *Diff_Diff) GetDstFileName() string {
	if x != nil {
		return x.DstFileName
	}
	return ""
}

func (x *Diff_Diff) GetAction() Diff_FileAction {
	if x != nil {
		return x.Action
	}
	return Diff_ADDED
}

type Diff_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Diff_Options) Reset() {
	*x = Diff_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diff_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff_Options) ProtoMessage() {}

func (x *Diff_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff_Options.ProtoReflect.Descriptor instead.
func (*Diff_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{6, 3}
}

func (x *Diff_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Diff_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Stash_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch  string         `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Options *Stash_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Stash_Request) Reset() {
	*x = Stash_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stash_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stash_Request) ProtoMessage() {}

func (x *Stash_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stash_Request.ProtoReflect.Descriptor instead.
func (*Stash_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Stash_Request) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Stash_Request) GetOptions() *Stash_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Stash_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stash_Response) Reset() {
	*x = Stash_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stash_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stash_Response) ProtoMessage() {}

func (x *Stash_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stash_Response.ProtoReflect.Descriptor instead.
func (*Stash_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{7, 1}
}

type Stash_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Stash_Options) Reset() {
	*x = Stash_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stash_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stash_Options) ProtoMessage() {}

func (x *Stash_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stash_Options.ProtoReflect.Descriptor instead.
func (*Stash_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{7, 2}
}

func (x *Stash_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Stash_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Checkout_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch  string            `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Options *Checkout_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Checkout_Request) Reset() {
	*x = Checkout_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checkout_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout_Request) ProtoMessage() {}

func (x *Checkout_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout_Request.ProtoReflect.Descriptor instead.
func (*Checkout_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Checkout_Request) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Checkout_Request) GetOptions() *Checkout_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Checkout_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Checkout_Response) Reset() {
	*x = Checkout_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checkout_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout_Response) ProtoMessage() {}

func (x *Checkout_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout_Response.ProtoReflect.Descriptor instead.
func (*Checkout_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{8, 1}
}

type Checkout_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Checkout_Options) Reset() {
	*x = Checkout_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checkout_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout_Options) ProtoMessage() {}

func (x *Checkout_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout_Options.ProtoReflect.Descriptor instead.
func (*Checkout_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{8, 2}
}

func (x *Checkout_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Checkout_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Watch_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Options *Watch_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Watch_Request) Reset() {
	*x = Watch_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch_Request) ProtoMessage() {}

func (x *Watch_Request) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch_Request.ProtoReflect.Descriptor instead.
func (*Watch_Request) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Watch_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Watch_Request) GetOptions() *Watch_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Watch_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BranchObj *BranchObject   `protobuf:"bytes,1,opt,name=branchObj,proto3" json:"branchObj,omitempty"`
	EventType Watch_EventType `protobuf:"varint,2,opt,name=eventType,proto3,enum=branchpb.Watch_EventType" json:"eventType,omitempty"`
}

func (x *Watch_Response) Reset() {
	*x = Watch_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch_Response) ProtoMessage() {}

func (x *Watch_Response) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch_Response.ProtoReflect.Descriptor instead.
func (*Watch_Response) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{9, 1}
}

func (x *Watch_Response) GetBranchObj() *BranchObject {
	if x != nil {
		return x.BranchObj
	}
	return nil
}

func (x *Watch_Response) GetEventType() Watch_EventType {
	if x != nil {
		return x.EventType
	}
	return Watch_ERROR
}

type Watch_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
	Watch          bool   `protobuf:"varint,3,opt,name=watch,proto3" json:"watch,omitempty"` // indicate watch only, otherwise list and watch is used
	Trace          string `protobuf:"bytes,4,opt,name=trace,proto3" json:"trace,omitempty"`
	Origin         string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *Watch_Options) Reset() {
	*x = Watch_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch_Options) ProtoMessage() {}

func (x *Watch_Options) ProtoReflect() protoreflect.Message {
	mi := &file_branch_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch_Options.ProtoReflect.Descriptor instead.
func (*Watch_Options) Descriptor() ([]byte, []int) {
	return file_branch_proto_rawDescGZIP(), []int{9, 2}
}

func (x *Watch_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Watch_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

func (x *Watch_Options) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *Watch_Options) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

func (x *Watch_Options) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

var File_branch_proto protoreflect.FileDescriptor

var file_branch_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x22, 0x42, 0x0a, 0x0c, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x22, 0xdb, 0x03, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x1a, 0x52, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x2f, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x67, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x62,
	0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x70, 0x62, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x6f,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67,
	0x73, 0x1a, 0x95, 0x01, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x2e, 0x0a, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xde, 0x01, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0d,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0d, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x55, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x32, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x55, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x32, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xde, 0x01, 0x0a, 0x05, 0x4d, 0x65,
	0x72, 0x67, 0x65, 0x1a, 0x78, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x72, 0x63, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x72, 0x63, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x64, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xba, 0x03, 0x0a, 0x04, 0x44,
	0x69, 0x66, 0x66, 0x1a, 0x77, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x72, 0x63, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x72, 0x63, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x64, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x2e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x35, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x64, 0x69, 0x66, 0x66,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52, 0x05, 0x64, 0x69,
	0x66, 0x66, 0x73, 0x1a, 0x7d, 0x0a, 0x04, 0x44, 0x69, 0x66, 0x66, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x72, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x72, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x31, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x22, 0x32, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x4d, 0x4f, 0x44, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x22, 0xba, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x73,
	0x68, 0x1a, 0x54, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x73, 0x68, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x22, 0xc0, 0x01, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x1a, 0x57, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x12, 0x34, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xb2, 0x03, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x1a, 0x4c, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x79, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x4f, 0x62,
	0x6a, 0x12, 0x37, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x93, 0x01, 0x0a, 0x07, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x22, 0x4a, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x44, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c,
	0x0a, 0x08, 0x42, 0x4f, 0x4f, 0x4b, 0x4d, 0x41, 0x52, 0x4b, 0x10, 0x04, 0x32, 0xf9, 0x04, 0x0a,
	0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x36, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x15,
	0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x05,
	0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62,
	0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x44, 0x69,
	0x66, 0x66, 0x12, 0x16, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x44, 0x69,
	0x66, 0x66, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x73, 0x68, 0x12, 0x17,
	0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x73, 0x68, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x73, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12,
	0x1a, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0b, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x62, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x17, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x66, 0x6f, 0x72, 0x6d, 0x2d, 0x64, 0x65, 0x76,
	0x2f, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_branch_proto_rawDescOnce sync.Once
	file_branch_proto_rawDescData = file_branch_proto_rawDesc
)

func file_branch_proto_rawDescGZIP() []byte {
	file_branch_proto_rawDescOnce.Do(func() {
		file_branch_proto_rawDescData = protoimpl.X.CompressGZIP(file_branch_proto_rawDescData)
	})
	return file_branch_proto_rawDescData
}

var file_branch_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_branch_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_branch_proto_goTypes = []interface{}{
	(Diff_FileAction)(0),      // 0: branchpb.Diff.FileAction
	(Watch_EventType)(0),      // 1: branchpb.Watch.EventType
	(*BranchObject)(nil),      // 2: branchpb.BranchObject
	(*Get)(nil),               // 3: branchpb.Get
	(*List)(nil),              // 4: branchpb.List
	(*Create)(nil),            // 5: branchpb.Create
	(*Delete)(nil),            // 6: branchpb.Delete
	(*Merge)(nil),             // 7: branchpb.Merge
	(*Diff)(nil),              // 8: branchpb.Diff
	(*Stash)(nil),             // 9: branchpb.Stash
	(*Checkout)(nil),          // 10: branchpb.Checkout
	(*Watch)(nil),             // 11: branchpb.Watch
	(*Get_Request)(nil),       // 12: branchpb.Get.Request
	(*Get_Response)(nil),      // 13: branchpb.Get.Response
	(*Get_Log)(nil),           // 14: branchpb.Get.Log
	(*Get_File)(nil),          // 15: branchpb.Get.File
	(*Get_Options)(nil),       // 16: branchpb.Get.Options
	(*List_Request)(nil),      // 17: branchpb.List.Request
	(*List_Response)(nil),     // 18: branchpb.List.Response
	(*List_Options)(nil),      // 19: branchpb.List.Options
	(*Create_Request)(nil),    // 20: branchpb.Create.Request
	(*Create_Response)(nil),   // 21: branchpb.Create.Response
	(*Create_Options)(nil),    // 22: branchpb.Create.Options
	(*Delete_Request)(nil),    // 23: branchpb.Delete.Request
	(*Delete_Response)(nil),   // 24: branchpb.Delete.Response
	(*Delete_Options)(nil),    // 25: branchpb.Delete.Options
	(*Merge_Request)(nil),     // 26: branchpb.Merge.Request
	(*Merge_Response)(nil),    // 27: branchpb.Merge.Response
	(*Merge_Options)(nil),     // 28: branchpb.Merge.Options
	(*Diff_Request)(nil),      // 29: branchpb.Diff.Request
	(*Diff_Response)(nil),     // 30: branchpb.Diff.Response
	(*Diff_Diff)(nil),         // 31: branchpb.Diff.Diff
	(*Diff_Options)(nil),      // 32: branchpb.Diff.Options
	(*Stash_Request)(nil),     // 33: branchpb.Stash.Request
	(*Stash_Response)(nil),    // 34: branchpb.Stash.Response
	(*Stash_Options)(nil),     // 35: branchpb.Stash.Options
	(*Checkout_Request)(nil),  // 36: branchpb.Checkout.Request
	(*Checkout_Response)(nil), // 37: branchpb.Checkout.Response
	(*Checkout_Options)(nil),  // 38: branchpb.Checkout.Options
	(*Watch_Request)(nil),     // 39: branchpb.Watch.Request
	(*Watch_Response)(nil),    // 40: branchpb.Watch.Response
	(*Watch_Options)(nil),     // 41: branchpb.Watch.Options
}
var file_branch_proto_depIdxs = []int32{
	16, // 0: branchpb.Get.Request.options:type_name -> branchpb.Get.Options
	2,  // 1: branchpb.Get.Response.branchObj:type_name -> branchpb.BranchObject
	14, // 2: branchpb.Get.Response.logs:type_name -> branchpb.Get.Log
	19, // 3: branchpb.List.Request.options:type_name -> branchpb.List.Options
	2,  // 4: branchpb.List.Response.branchObjects:type_name -> branchpb.BranchObject
	22, // 5: branchpb.Create.Request.options:type_name -> branchpb.Create.Options
	25, // 6: branchpb.Delete.Request.options:type_name -> branchpb.Delete.Options
	28, // 7: branchpb.Merge.Request.options:type_name -> branchpb.Merge.Options
	32, // 8: branchpb.Diff.Request.options:type_name -> branchpb.Diff.Options
	31, // 9: branchpb.Diff.Response.diffs:type_name -> branchpb.Diff.Diff
	0,  // 10: branchpb.Diff.Diff.Action:type_name -> branchpb.Diff.FileAction
	35, // 11: branchpb.Stash.Request.options:type_name -> branchpb.Stash.Options
	38, // 12: branchpb.Checkout.Request.options:type_name -> branchpb.Checkout.Options
	41, // 13: branchpb.Watch.Request.options:type_name -> branchpb.Watch.Options
	2,  // 14: branchpb.Watch.Response.branchObj:type_name -> branchpb.BranchObject
	1,  // 15: branchpb.Watch.Response.eventType:type_name -> branchpb.Watch.EventType
	12, // 16: branchpb.Branch.Get:input_type -> branchpb.Get.Request
	17, // 17: branchpb.Branch.List:input_type -> branchpb.List.Request
	20, // 18: branchpb.Branch.Create:input_type -> branchpb.Create.Request
	23, // 19: branchpb.Branch.Delete:input_type -> branchpb.Delete.Request
	26, // 20: branchpb.Branch.Merge:input_type -> branchpb.Merge.Request
	29, // 21: branchpb.Branch.Diff:input_type -> branchpb.Diff.Request
	33, // 22: branchpb.Branch.Stash:input_type -> branchpb.Stash.Request
	36, // 23: branchpb.Branch.Checkout:input_type -> branchpb.Checkout.Request
	12, // 24: branchpb.Branch.StreamFiles:input_type -> branchpb.Get.Request
	39, // 25: branchpb.Branch.Watch:input_type -> branchpb.Watch.Request
	13, // 26: branchpb.Branch.Get:output_type -> branchpb.Get.Response
	18, // 27: branchpb.Branch.List:output_type -> branchpb.List.Response
	21, // 28: branchpb.Branch.Create:output_type -> branchpb.Create.Response
	24, // 29: branchpb.Branch.Delete:output_type -> branchpb.Delete.Response
	27, // 30: branchpb.Branch.Merge:output_type -> branchpb.Merge.Response
	30, // 31: branchpb.Branch.Diff:output_type -> branchpb.Diff.Response
	34, // 32: branchpb.Branch.Stash:output_type -> branchpb.Stash.Response
	37, // 33: branchpb.Branch.Checkout:output_type -> branchpb.Checkout.Response
	15, // 34: branchpb.Branch.StreamFiles:output_type -> branchpb.Get.File
	40, // 35: branchpb.Branch.Watch:output_type -> branchpb.Watch.Response
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_branch_proto_init() }
func file_branch_proto_init() {
	if File_branch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_branch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checkout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merge_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merge_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merge_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diff_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diff_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diff_Diff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diff_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stash_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stash_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stash_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checkout_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checkout_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checkout_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_branch_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_branch_proto_goTypes,
		DependencyIndexes: file_branch_proto_depIdxs,
		EnumInfos:         file_branch_proto_enumTypes,
		MessageInfos:      file_branch_proto_msgTypes,
	}.Build()
	File_branch_proto = out.File
	file_branch_proto_rawDesc = nil
	file_branch_proto_goTypes = nil
	file_branch_proto_depIdxs = nil
}
