//
//Copyright 2024 Nokia.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: choreo.proto

package choreopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Watch_EventType int32

const (
	Watch_ERROR    Watch_EventType = 0
	Watch_ADDED    Watch_EventType = 1
	Watch_MODIFIED Watch_EventType = 2
	Watch_DELETED  Watch_EventType = 3
	Watch_BOOKMARK Watch_EventType = 4
)

// Enum value maps for Watch_EventType.
var (
	Watch_EventType_name = map[int32]string{
		0: "ERROR",
		1: "ADDED",
		2: "MODIFIED",
		3: "DELETED",
		4: "BOOKMARK",
	}
	Watch_EventType_value = map[string]int32{
		"ERROR":    0,
		"ADDED":    1,
		"MODIFIED": 2,
		"DELETED":  3,
		"BOOKMARK": 4,
	}
)

func (x Watch_EventType) Enum() *Watch_EventType {
	p := new(Watch_EventType)
	*p = x
	return p
}

func (x Watch_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Watch_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_choreo_proto_enumTypes[0].Descriptor()
}

func (Watch_EventType) Type() protoreflect.EnumType {
	return &file_choreo_proto_enumTypes[0]
}

func (x Watch_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Watch_EventType.Descriptor instead.
func (Watch_EventType) EnumDescriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{3, 0}
}

// 3 usages:
// 1. dev with human git -> production = false, path is set
// 2. dev with choreo git -> production = false, branch, url, ref, dir is set
// 3. prod ->  production = true, url, ref, dir is set; (branch is irrelevant)
type ChoreoContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Production bool   `protobuf:"varint,1,opt,name=production,proto3" json:"production,omitempty"` // drives continuous mode
	Path       string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`              // when we supply this this is a manual path -> dev with human git
	Branch     string `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`          // dev with choreo git
	Url        string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Ref        string `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`
	Directory  string `protobuf:"bytes,6,opt,name=directory,proto3" json:"directory,omitempty"`
	Secret     string `protobuf:"bytes,7,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *ChoreoContext) Reset() {
	*x = ChoreoContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoreoContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoreoContext) ProtoMessage() {}

func (x *ChoreoContext) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoreoContext.ProtoReflect.Descriptor instead.
func (*ChoreoContext) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{0}
}

func (x *ChoreoContext) GetProduction() bool {
	if x != nil {
		return x.Production
	}
	return false
}

func (x *ChoreoContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChoreoContext) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ChoreoContext) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ChoreoContext) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ChoreoContext) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *ChoreoContext) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Get) Reset() {
	*x = Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{1}
}

type Apply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Apply) Reset() {
	*x = Apply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Apply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apply) ProtoMessage() {}

func (x *Apply) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apply.ProtoReflect.Descriptor instead.
func (*Apply) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{2}
}

type Watch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Watch) Reset() {
	*x = Watch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch) ProtoMessage() {}

func (x *Watch) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch.ProtoReflect.Descriptor instead.
func (*Watch) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{3}
}

type Commit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Commit) Reset() {
	*x = Commit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{4}
}

type Push struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Push) Reset() {
	*x = Push{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Push) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push) ProtoMessage() {}

func (x *Push) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Push.ProtoReflect.Descriptor instead.
func (*Push) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{5}
}

type Get_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Get_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Get_Request) Reset() {
	*x = Get_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Request) ProtoMessage() {}

func (x *Get_Request) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Request.ProtoReflect.Descriptor instead.
func (*Get_Request) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Get_Request) GetOptions() *Get_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Get_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChoreoContext *ChoreoContext `protobuf:"bytes,1,opt,name=choreoContext,proto3" json:"choreoContext,omitempty"`
	Status        bool           `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string         `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Get_Response) Reset() {
	*x = Get_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Response) ProtoMessage() {}

func (x *Get_Response) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Response.ProtoReflect.Descriptor instead.
func (*Get_Response) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Get_Response) GetChoreoContext() *ChoreoContext {
	if x != nil {
		return x.ChoreoContext
	}
	return nil
}

func (x *Get_Response) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Get_Response) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Get_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Get_Options) Reset() {
	*x = Get_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Options) ProtoMessage() {}

func (x *Get_Options) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Options.ProtoReflect.Descriptor instead.
func (*Get_Options) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Get_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Get_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Apply_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChoreoContext *ChoreoContext `protobuf:"bytes,1,opt,name=choreoContext,proto3" json:"choreoContext,omitempty"`
	Options       *Apply_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Apply_Request) Reset() {
	*x = Apply_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Apply_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apply_Request) ProtoMessage() {}

func (x *Apply_Request) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apply_Request.ProtoReflect.Descriptor instead.
func (*Apply_Request) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Apply_Request) GetChoreoContext() *ChoreoContext {
	if x != nil {
		return x.ChoreoContext
	}
	return nil
}

func (x *Apply_Request) GetOptions() *Apply_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Apply_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Apply_Response) Reset() {
	*x = Apply_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Apply_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apply_Response) ProtoMessage() {}

func (x *Apply_Response) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apply_Response.ProtoReflect.Descriptor instead.
func (*Apply_Response) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{2, 1}
}

type Apply_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Apply_Options) Reset() {
	*x = Apply_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Apply_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apply_Options) ProtoMessage() {}

func (x *Apply_Options) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apply_Options.ProtoReflect.Descriptor instead.
func (*Apply_Options) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Apply_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Apply_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Watch_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Watch_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Watch_Request) Reset() {
	*x = Watch_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch_Request) ProtoMessage() {}

func (x *Watch_Request) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch_Request.ProtoReflect.Descriptor instead.
func (*Watch_Request) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Watch_Request) GetOptions() *Watch_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Watch_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChoreoContext *ChoreoContext  `protobuf:"bytes,1,opt,name=choreoContext,proto3" json:"choreoContext,omitempty"`
	EventType     Watch_EventType `protobuf:"varint,2,opt,name=eventType,proto3,enum=choreopb.Watch_EventType" json:"eventType,omitempty"`
}

func (x *Watch_Response) Reset() {
	*x = Watch_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch_Response) ProtoMessage() {}

func (x *Watch_Response) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch_Response.ProtoReflect.Descriptor instead.
func (*Watch_Response) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Watch_Response) GetChoreoContext() *ChoreoContext {
	if x != nil {
		return x.ChoreoContext
	}
	return nil
}

func (x *Watch_Response) GetEventType() Watch_EventType {
	if x != nil {
		return x.EventType
	}
	return Watch_ERROR
}

type Watch_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watch          bool   `protobuf:"varint,1,opt,name=watch,proto3" json:"watch,omitempty"` // indicate watch only, otherwise list and watch is used
	ProxyName      string `protobuf:"bytes,2,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,3,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Watch_Options) Reset() {
	*x = Watch_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watch_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch_Options) ProtoMessage() {}

func (x *Watch_Options) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch_Options.ProtoReflect.Descriptor instead.
func (*Watch_Options) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Watch_Options) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *Watch_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Watch_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

type Commit_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Options *Commit_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Commit_Request) Reset() {
	*x = Commit_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit_Request) ProtoMessage() {}

func (x *Commit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit_Request.ProtoReflect.Descriptor instead.
func (*Commit_Request) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Commit_Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Commit_Request) GetOptions() *Commit_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Commit_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Commit_Response) Reset() {
	*x = Commit_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit_Response) ProtoMessage() {}

func (x *Commit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit_Response.ProtoReflect.Descriptor instead.
func (*Commit_Response) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Commit_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Commit_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
	Push           bool   `protobuf:"varint,3,opt,name=push,proto3" json:"push,omitempty"` // when the push is set the commit is push
}

func (x *Commit_Options) Reset() {
	*x = Commit_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit_Options) ProtoMessage() {}

func (x *Commit_Options) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit_Options.ProtoReflect.Descriptor instead.
func (*Commit_Options) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Commit_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Commit_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

func (x *Commit_Options) GetPush() bool {
	if x != nil {
		return x.Push
	}
	return false
}

type Push_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Push_Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Push_Request) Reset() {
	*x = Push_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Push_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push_Request) ProtoMessage() {}

func (x *Push_Request) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Push_Request.ProtoReflect.Descriptor instead.
func (*Push_Request) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Push_Request) GetOptions() *Push_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Push_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Push_Response) Reset() {
	*x = Push_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Push_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push_Response) ProtoMessage() {}

func (x *Push_Response) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Push_Response.ProtoReflect.Descriptor instead.
func (*Push_Response) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{5, 1}
}

type Push_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName      string `protobuf:"bytes,1,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	ProxyNamespace string `protobuf:"bytes,2,opt,name=proxyNamespace,proto3" json:"proxyNamespace,omitempty"`
}

func (x *Push_Options) Reset() {
	*x = Push_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_choreo_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Push_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push_Options) ProtoMessage() {}

func (x *Push_Options) ProtoReflect() protoreflect.Message {
	mi := &file_choreo_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Push_Options.ProtoReflect.Descriptor instead.
func (*Push_Options) Descriptor() ([]byte, []int) {
	return file_choreo_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Push_Options) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *Push_Options) GetProxyNamespace() string {
	if x != nil {
		return x.ProxyNamespace
	}
	return ""
}

var File_choreo_proto protoreflect.FileDescriptor

var file_choreo_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x22, 0xb5, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x6f,
	0x72, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x22, 0x8d, 0x02, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x1a, 0x3a, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x79, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x0d, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f,
	0x70, 0x62, 0x2e, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x52, 0x0d, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a,
	0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0xe1, 0x01, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x1a, 0x7b, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0d, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63,
	0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x0d, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62,
	0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x22, 0xfd, 0x02, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x3c,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x82, 0x01, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x63, 0x68, 0x6f,
	0x72, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x6f, 0x72,
	0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x0d, 0x63, 0x68, 0x6f, 0x72, 0x65,
	0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x68,
	0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x1a, 0x65, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x4a, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d,
	0x4f, 0x44, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c,
	0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x4f, 0x4f, 0x4b, 0x4d, 0x41,
	0x52, 0x4b, 0x10, 0x04, 0x22, 0xec, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x1a,
	0x57, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x63,
	0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x75, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70,
	0x75, 0x73, 0x68, 0x22, 0xa0, 0x01, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x1a, 0x3b, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65,
	0x6f, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x4f, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x32, 0xfa, 0x01, 0x0a, 0x06, 0x43, 0x68, 0x6f, 0x72, 0x65,
	0x6f, 0x12, 0x36, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65,
	0x6f, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x05, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x12, 0x17, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x68,
	0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x12, 0x18, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x68,
	0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68,
	0x12, 0x16, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x6f, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x65,
	0x6f, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x66, 0x6f, 0x72, 0x6d, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x68, 0x6f, 0x72,
	0x65, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x6f,
	0x72, 0x65, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_choreo_proto_rawDescOnce sync.Once
	file_choreo_proto_rawDescData = file_choreo_proto_rawDesc
)

func file_choreo_proto_rawDescGZIP() []byte {
	file_choreo_proto_rawDescOnce.Do(func() {
		file_choreo_proto_rawDescData = protoimpl.X.CompressGZIP(file_choreo_proto_rawDescData)
	})
	return file_choreo_proto_rawDescData
}

var file_choreo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_choreo_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_choreo_proto_goTypes = []interface{}{
	(Watch_EventType)(0),    // 0: choreopb.Watch.EventType
	(*ChoreoContext)(nil),   // 1: choreopb.ChoreoContext
	(*Get)(nil),             // 2: choreopb.Get
	(*Apply)(nil),           // 3: choreopb.Apply
	(*Watch)(nil),           // 4: choreopb.Watch
	(*Commit)(nil),          // 5: choreopb.Commit
	(*Push)(nil),            // 6: choreopb.Push
	(*Get_Request)(nil),     // 7: choreopb.Get.Request
	(*Get_Response)(nil),    // 8: choreopb.Get.Response
	(*Get_Options)(nil),     // 9: choreopb.Get.Options
	(*Apply_Request)(nil),   // 10: choreopb.Apply.Request
	(*Apply_Response)(nil),  // 11: choreopb.Apply.Response
	(*Apply_Options)(nil),   // 12: choreopb.Apply.Options
	(*Watch_Request)(nil),   // 13: choreopb.Watch.Request
	(*Watch_Response)(nil),  // 14: choreopb.Watch.Response
	(*Watch_Options)(nil),   // 15: choreopb.Watch.Options
	(*Commit_Request)(nil),  // 16: choreopb.Commit.Request
	(*Commit_Response)(nil), // 17: choreopb.Commit.Response
	(*Commit_Options)(nil),  // 18: choreopb.Commit.Options
	(*Push_Request)(nil),    // 19: choreopb.Push.Request
	(*Push_Response)(nil),   // 20: choreopb.Push.Response
	(*Push_Options)(nil),    // 21: choreopb.Push.Options
}
var file_choreo_proto_depIdxs = []int32{
	9,  // 0: choreopb.Get.Request.options:type_name -> choreopb.Get.Options
	1,  // 1: choreopb.Get.Response.choreoContext:type_name -> choreopb.ChoreoContext
	1,  // 2: choreopb.Apply.Request.choreoContext:type_name -> choreopb.ChoreoContext
	12, // 3: choreopb.Apply.Request.options:type_name -> choreopb.Apply.Options
	15, // 4: choreopb.Watch.Request.options:type_name -> choreopb.Watch.Options
	1,  // 5: choreopb.Watch.Response.choreoContext:type_name -> choreopb.ChoreoContext
	0,  // 6: choreopb.Watch.Response.eventType:type_name -> choreopb.Watch.EventType
	18, // 7: choreopb.Commit.Request.options:type_name -> choreopb.Commit.Options
	21, // 8: choreopb.Push.Request.options:type_name -> choreopb.Push.Options
	7,  // 9: choreopb.Choreo.Get:input_type -> choreopb.Get.Request
	10, // 10: choreopb.Choreo.Apply:input_type -> choreopb.Apply.Request
	16, // 11: choreopb.Choreo.Commit:input_type -> choreopb.Commit.Request
	19, // 12: choreopb.Choreo.Push:input_type -> choreopb.Push.Request
	8,  // 13: choreopb.Choreo.Get:output_type -> choreopb.Get.Response
	11, // 14: choreopb.Choreo.Apply:output_type -> choreopb.Apply.Response
	17, // 15: choreopb.Choreo.Commit:output_type -> choreopb.Commit.Response
	20, // 16: choreopb.Choreo.Push:output_type -> choreopb.Push.Response
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_choreo_proto_init() }
func file_choreo_proto_init() {
	if File_choreo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_choreo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoreoContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Apply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Push); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Apply_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Apply_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Apply_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watch_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commit_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commit_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commit_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Push_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Push_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_choreo_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Push_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_choreo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_choreo_proto_goTypes,
		DependencyIndexes: file_choreo_proto_depIdxs,
		EnumInfos:         file_choreo_proto_enumTypes,
		MessageInfos:      file_choreo_proto_msgTypes,
	}.Build()
	File_choreo_proto = out.File
	file_choreo_proto_rawDesc = nil
	file_choreo_proto_goTypes = nil
	file_choreo_proto_depIdxs = nil
}
