# Copyright 2024 Nokia
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
---
name: goreleaser ci
on:
  push:
#    branches:
#      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      goreleaser: ${{ steps.filter.outputs.goreleaser }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: run go releaser
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
