# Copyright 2024 Nokia
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
---
name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "!releases/**"
env:
  GOVER: 1.22.2

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}
      - run: go test -cover ./...
        env:
          CGO_ENABLED: 0
      #- name: golangci-lint
      #  uses: golangci/golangci-lint-action@v6
      #  with:
      #    version: v1.38
      # run staticcheck